# Generated by Django 6.0.7 on 2026-07-28 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("slack_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "slack_username",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "slack_pfp_url",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hackclub_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
