# Generated by Django 6.0.7 on 2026-07-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twisted_site", "0005_project_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_name",
            field=models.CharField(max_length=50),
        ),
    ]
