# Generated by Django 6.0.7 on 2026-08-04 14:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0009_uploadedimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedImage',
            new_name='UploadedFile',
        ),
    ]
