# Generated by Django 6.0.7 on 2026-08-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0011_journal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
