# Generated by Django 6.0.7 on 2026-08-08 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0012_project_repo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('t1_updated_at', models.DateTimeField(default=None, null=True)),
                ('t2_updated_at', models.DateTimeField(default=None, null=True)),
                ('t1_message', models.TextField(blank=True, default='')),
                ('t2_message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('created', 'Newly created'), ('rejected', 'Rejected ship'), ('reqchecked', 'Checked by T1'), ('approved', 'Approved by T2')], default='created', max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ships', to='twisted_site.project')),
            ],
        ),
    ]
