# Generated by Django 6.0.7 on 2026-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0013_projectship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
