# Generated by Django 6.0.7 on 2026-08-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0014_profile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_theme',
            field=models.BooleanField(default=True),
        ),
    ]
