# Generated by Django 6.0.7 on 2026-08-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0015_profile_dark_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ysws_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
