# Generated by Django 6.0.7 on 2026-08-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0019_remove_projectship_status_projectship_final_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twists',
            field=models.IntegerField(default=0),
        ),
    ]
