# Generated by Django 6.0.7 on 2026-09-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0024_auditlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='additional_context',
            field=models.JSONField(default=None, null=True),
        ),
    ]
