# Generated by Django 6.0.7 on 2026-09-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0025_alter_auditlog_additional_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='playable_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
