# Generated by Django 6.0.7 on 2026-09-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twisted_site", "0026_project_playable_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hca_access_token",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="project",
            name="screenshot_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
