# Generated by Django 6.0.7 on 2026-09-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0033_project_hackatime_project_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='country_cached_until',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
