# Generated by Django 6.0.7 on 2026-09-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0035_pathwaygroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathwaytimespent',
            name='golden_twists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pathwaytimespent',
            name='unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
