# Generated by Django 6.0.7 on 2026-09-22 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("twisted_site", "0034_profile_country_profile_country_cached_until"),
        ("twisted_site", "0035_remove_pathwaygroup"),
    ]

    operations = []
