# Generated by Django 6.0.7 on 2026-09-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0036_merge_20260922_1730'),
        ('twisted_site', '0038_profile_region'),
    ]

    operations = [
    ]
