# Generated by Django 6.0.7 on 2026-09-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0041_shopitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestaffpermissions',
            name='view_projects',
            field=models.BooleanField(default=False),
        ),
    ]
