# Generated by Django 6.0.7 on 2026-09-30 14:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0044_ariwebhookdelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(blank=True, default='', max_length=200)),
                ('price_paid', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending fulfillment'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('staff_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='twisted_site.shopitem')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='twisted_site.pathway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
