# Generated by Django 6.0.7 on 2026-09-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0045_shoporder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilestaffpermissions',
            name='manage_review',
        ),
        migrations.RemoveField(
            model_name='profilestaffpermissions',
            name='view_review',
        ),
        migrations.RemoveField(
            model_name='projectship',
            name='final_audit_note',
        ),
        migrations.RemoveField(
            model_name='projectship',
            name='final_note_to_maker',
        ),
        migrations.RemoveField(
            model_name='projectship',
            name='final_status',
        ),
    ]
