# Generated by Django 6.0.7 on 2026-10-01 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0047_currencylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathwayCurrencyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_balance', models.IntegerField()),
                ('difference', models.IntegerField()),
                ('note', models.CharField(max_length=999)),
                ('pathway_ts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_logs', to='twisted_site.pathwaytimespent')),
            ],
        ),
    ]
