# Generated by Django 6.0.7 on 2026-10-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0048_pathwaycurrencylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilestaffpermissions',
            name='view_review',
        ),
    ]
