# Generated by Django 6.0.7 on 2026-10-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twisted_site', '0049_remove_profilestaffpermissions_view_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestaffpermissions',
            name='view_review',
            field=models.BooleanField(default=False),
        ),
    ]
